apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: springboot
  name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: dockerhandson/spring-boot-mongo:latest
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080       
---
# Load Balancer Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboot
  name: springboot
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: springboot

---

# creating a PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebspvc-mongo
spec:
  storageClassName: default 
# since i created a kubeernetes cluster usinng kops,there is a storage class configure for this cluster.here the storage class is responsible for creating a dynamic volume.default class is using aws provisioner and create ebs volume    
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


---
# Mongo host path rc
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      volumes:
      - name: ebspvc
        persistentVolumeClaim:
          claimName: ebspvc-mongo    
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: ebspvc
          mountPath: /data/db
...
---
# Mongo Node Port RC
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
...
